### ISSUE TITLE
cannot find input data

### ISSUE THREAD

**Issue by zuixiaosanlang** [cong-yi/DualMesh-UDF#1]
there is no input data like pointcloud in the example.

i have a pointcloud data, and want to get the mesh,

how to use the dmudf to get the mesh??

donnot know how to change my pointcloud data to xxx.pth

**Comment by cong-yi** [comment]
Our current work is designed for extracting surfaces from unsigned distance fields and does not apply to point clouds directly. To use our code, you need to first turn your point cloud into a UDF.

**Comment by LogWell** [comment]
You can use the method described in "Deep Implicit Moving Least-Squares Functions for 3D Reconstruction" to convert the point cloud into UDF (with slight modifications)
