### ISSUE TITLE
How to get a unflipped mesh?

### ISSUE THREAD

**Issue by LogWell** [cong-yi/DualMesh-UDF#2]
Why does the mesh generated by `python example/test.py --pretrained ckpt/bimba.pth` have black areas:

![image](https://github.com/cong-yi/DualMesh-UDF/assets/34391447/82df34c0-0fd9-4122-95e4-da374be602e3)

**Comment by cong-yi** [comment]
Thank you for your interest in our project. When dealing with UDF fields, there is no theoretical guarantee for extracting a manifold mesh. For the resulting meshes, I recommend rendering them using double-face rendering. If you still want a watertight manifold mesh for other purposes, post-processing methods such as https://www.dgp.toronto.edu/projects/fast-winding-numbers/ can be employed.
